#!/bin/bash

export OMP_NUM_THREADS=16
export WORKLOAD_SIZE="high"
export FILENAME="results/fdm-$OMP_NUM_THREADS-$WORKLOAD_SIZE.out"

mkdir -p results
./mdf < fdm-$WORKLOAD_SIZE.in | ./create_results.sh
